{% set name = "ml4xcube" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./

build:
  noarch: python
  # Change the directory to the ml4xcube directory before running pip install
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - conda-forge::xcube

test:
  imports:
    - ml4xcube

about:
  home: https://github.com/deepesdl/ML-Toolkits/tree/develop/mltools
  license: MIT
  license_family: MIT
  license_file: LICENSE  # Ensure a LICENSE file is present in your source code and specify its relative path here
  summary: 'ML package for data cubes'
  description: 'ML package for data cubes'
  doc_url:  # Optional documentation URL
  dev_url:  # Optional development URL

extra:
  recipe-maintainers:
    - Julia310
