{% set name = "mltools" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/deepesdl/ML-Toolkits/archive/refs/heads/develop.zip  # Update this URL to point to your source code archive

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bokeh>=2.4.3,<3
    - dask=2024.2.1
    - dask-core=2024.2.1
    - jinja2=3.1.3
    - mypy_extensions=1.0.0
    - numpy >=1.24
    - pandas >=2.2
    - scikit-learn >1.3.1
    - xarray=2024.2.0
    - zarr>2.11
    - rechunker>=0.5.1

test:
  imports:
    - mltools

about:
  home: https://github.com/deepesdl/ML-Toolkits/tree/develop/mltools
  license: MIT
  license_family: MIT
  license_file: LICENSE  # Ensure a LICENSE file is present in your source code and specify its relative path here
  summary: 'ML package for data cubes'
  description: 'ML package for data cubes'
  doc_url:  # Optional documentation URL
  dev_url:  # Optional development URL

extra:
  recipe-maintainers:
    - Julia310
